---

- name: Stop EC2 instance
  ec2:
    instance_ids: '{{ instance_ids }}'
#    region: '{{ region }}'
    region: 'us-east-1'
    state: stopped
    wait: True
    vpc_subnet_id: '{{subnet}}'
   # assign_public_ip: yes
