---

- name: This is UserGroup creation YAML
  hosts: all
  user: rahul
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: Create user
    user: name=test1 uid=777 shell=/bin/bash comment="Test user" state=present

  - name: Create Group
    group: name=testgrp gid=999 state=present

...
